version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app"
    target-branch: "develop"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[skip ci] "
    schedule:
      interval: "weekly"
  # - package-ecosystem: "github-actions"
  #   directory: "/"
  #   target-branch: "develop"
  #   schedule:
  #     interval: "monthly"
  #   commit-message:
  #     prefix: "[skip ci] "
