require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '15.0'
install! 'cocoapods', :deterministic_uuids => false

production = ENV["PRODUCTION"] == "1"

# set deployment target to '> 9'
def change_deployment_target_for_xcode12(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end

def fix_fb_react_native_spec(installer)
  installer.pods_project.targets.each do |target|
    if target.name == 'FBReactNativeSpec'
      target.build_configurations.each do |config|
        if config.name == 'Debug' or config.name == 'Release'
          config.build_settings['NODE_BINARY'] = "$HOME/.anyenv/envs/nodenv/shims/node"
          # config.build_settings['NODE_BINARY'] = "/Users/mitsuharu/.anyenv/envs/nodenv/shims/node"
        end
      end
    end
  end
end

target 'ubepedia' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :production => production,
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'ubepediaTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
    change_deployment_target_for_xcode12(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
      end
    end

    fix_fb_react_native_spec(installer)

  end

end
